### ISSUE TITLE
Search function return same TOTP for all entries

### ISSUE THREAD

**Issue by kevinstsauveur** [bitwarden/authenticator-ios#117]
### Steps To Reproduce

1. Open Bitwarden Authenticator
2. Tap on the search bar and type text that returns one or more entries
3. TOTP results that are shown and copied when items are pressed are always "123456".

### Expected Result

Each code that is shown and copied when pressed should be calculated based on the corresponding Key, and not "123456"

### Actual Result

TOTP results that are shown and copied when items are pressed are always "123456", which is incorrect and does not match the expected behavior.

### Screenshots or Videos

![image](https://github.com/bitwarden/authenticator-ios/assets/25964106/3a2af2f2-6e00-4e9f-b59d-acfab6dc2efb)

### Build Version

2024.6.1(45)

### Environment Details

- Device : iPhone 13 Pro
- OS : 17.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by leonlazic** [comment]
Just found this as well.

**Comment by marcolaux** [comment]
Same here on iOS

**Comment by Neonwarden** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by alexghattas** [comment]
Have this issue as well - surprised it has not been fixed after a month of reporting it. Seems like a pretty critical bug.

**Comment by SergeantConfused** [comment]
Hello everyone,

This is being worked on in this [pull request](https://github.com/bitwarden/authenticator-ios/pull/119).

Thank you,
