### ISSUE TITLE
Hardcoded "123456" authentication code when searching for arbitrary service

### ISSUE THREAD

**Issue by Hajneken** [bitwarden/authenticator-ios#133]
### Steps To Reproduce

1. Tap on Search  
1. Type in Arbitrary Protected Service 
1. Result displays authentication code `123456` which is also copied to clipboard on tap

### Expected Result

Should display the correct authentication code displayed otherwise.

### Actual Result

Always shows authentication code `123456` which is wrong

### Screenshots or Videos

![example](https://github.com/user-attachments/assets/e6b499f3-e6eb-4344-9220-37cfd4f57790)

### Build Version

2024.6.1 (45)

### Environment Details

- Device: iPhone XS Max, iOS 17.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @Hajneken,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,
