### ISSUE TITLE
Bitwarden Authenticator cannot be opened in iPhone 16 Pro Max under iOS 18

### ISSUE THREAD

**Issue by tinyau** [bitwarden/authenticator-ios#159]
### Steps To Reproduce

1. Click "Bitwarden Authenticator" icon

### Expected Result

Bitwarden Authenticator app can be opened

### Actual Result

Keep staying in the loading screen.

![IMG_3510](https://github.com/user-attachments/assets/2aafa093-d37e-44e0-8213-14a08f4e39fa)

### Build Version

2024.6.1

### Environment Details

iPhone 16 Pro Max
iOS 18.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tinyau** [comment]
Tried to uninstall and reinstall the app and the problem is solved.

**Comment by brent20** [comment]
Just to be clear- this is duplicate of https://github.com/bitwarden/authenticator-ios/issues/94

And it is already fixed, a new release needs to be deployed.
