### ISSUE TITLE
Authenticator key with spaces doesn't work when entering it manually

### ISSUE THREAD

**Issue by lzukanovic** [bitwarden/authenticator-ios#183]
### Steps To Reproduce

Add authenticator to Google account:
1. Go to myaccount.google.com
2. Click Security
3. Click Authenticator
4. Click Add authenticator
5. Click "Can't scan it?"
Now you have a authenticator key to manually enter into the Bitwarden Authenticator. Notice how it says that "spaces don't matter".

Link Bitwarden Authenticator to Google account:
1. Open Bitwarden Authenticator
2. Go to 'Verification codes'
3. Tap on '+'
7. Tap on 'Enter key manually'
8. Enter some name, e.g. "Test"
9. Enter the key from the Google account (_including spaces_)
10. Tap on 'Add code'

### Expected Result

Successfully added verification code for Google account.

### Actual Result

Error: Cannot read key.

### Additional Context

If you manually remove the spaces in the key and try to add it again it works.

### Build Version

2024.6.1 (45)

### Environment Details

- Device: [iPhone 13]
- OS Version: [iOS 18.1]

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/authenticator-android/issues/199

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
